src/vivarium_gates_nutrition_optimization/constants/results.py, src/vivarium_gates_nutrition_optimization/model_specifications/model_spec.yaml, src/vivarium_gates_nutrition_optimization/results_processing/process_results.py
- *Category*:  observers
- *JIRA issue*: [MIC-4097](https://jira.ihme.washington.edu/browse/MIC-4097)
- *Research reference*:  https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.html#models
I edited the model spec, `results.py`, and `process_results.py` such that:
- there is no 'get_population' type aggregation being performed
- there is no sex or year stratification (per RT)
- stratification and observation happens through model spec changes.
Simulation can be run
`make_results works`
CI passes
=> Resolve MIC-4097: Model 0.0 Observers

src/vivarium_gates_nutrition_optimization/model_specifications/model_spec.yaml
- *Category*:  Observers
- *JIRA issue*: [MIC-4115](https://jira.ihme.washington.edu/browse/MIC-4115)
- *Research reference*:  [Pregnancy Concept Model](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.html#models)
Added Disease Observer
Pregnancy is getting observed
CI Passes
=> Add Disease Observer Model 0.1

src/vivarium_gates_nutrition_optimization/constants/data_keys.py, src/vivarium_gates_nutrition_optimization/data/loader.py
- *Category*: 
artifact
- *JIRA issue*: [MIC-4246](https://jira.ihme.washington.edu/browse/MIC-4246)
https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_nutrition_optimization/pregnancies/concept_model.html#models
The original Artifact Model 2.0 assumed that we were going to keep things pretty similar to IV Iron, but now we have an implementation that has a slightly different mix of data keys required.
In particular, we're breaking Hemorrhage into 2.1 (removing those keys), and we don't need PROBABILITY_FATAL or PROBABILITY_NONFATAL anymore, since standard VPH components will handle those transitions.
Also, we want CSMR and INCIDENCE RATE to take a form that can be used by DiseaseModel / DiseaseState, so we're going to scale by the …
=> Model2.0 Artifact Additions

src/vivarium_gates_nutrition_optimization/constants/data_keys.py, src/vivarium_gates_nutrition_optimization/data/loader.py
- *Category*: 
artifact
- *JIRA issue*: [MIC-4260](https://jira.ihme.washington.edu/browse/MIC-4260)
- [Maternal Hemorrhage Cause Model](https://vivarium-research.readthedocs.io/en/latest/models/causes/maternal_hemorrhage_incidence/index.html#cause-maternal-hemorrhage-incidence)
Add keys for Maternal hemorrhage: incidence rate, CSMR, and incident probability [(incidence - csmr ) / pregnancy incidence]
Artifact builds and has reasonable data for new keys
=> MIC-4260 Model 2.1 Artifact

src/vivarium_gates_nutrition_optimization/components/mortality.py
- *Category*: 
bugfix
- *JIRA issue*: [MIC-4264](https://jira.ihme.washington.edu/browse/MIC-4264)
- https://github.com/ihmeuw/vivarium_research/pull/1278
We were overcounting deaths because I did the state selection wrong. This changes it so that we properly select on the maternal_disorders state instead.
Confirmed with RT on bugfix run that this fixes the issue
=> Model 2.0 V&V Bugfix

src/vivarium_gates_nutrition_optimization/components/pregnancy.py
- *Category*: 
bugfix
- *JIRA issue*: [MIC-4314](https://jira.ihme.washington.edu/browse/MIC-4314)
We've been getting lucky it seems that pregnancy state transitions (to the parturition state) happen before maternal disorders / maternal hemorrhage transitions do. It is best to attain this behavior without being lucky. We also have to explicitly set an observation to occur between these two events, which makes it even more necessary.
Give DiseaseModel for Pregnancy a subclass with a lower (earlier) priority.
The simulation runs; the new listener registration is being called.
=> Add Pregnant Priority

setup.py, src/vivarium_gates_nutrition_optimization/constants/data_keys.py, src/vivarium_gates_nutrition_optimization/constants/data_values.py, src/vivarium_gates_nutrition_optimization/data/loader.py
- *Category*: 
artifact
- *JIRA issue*: [MIC-4324](https://jira.ihme.washington.edu/browse/MIC-4324)
- https://vivarium-research.readthedocs.io/en/latest/models/risk_correlation/maternal_bmi_hgb_birthweight/index.html#risk-correlation-maternal-bmi-hgb-birthweight
This provides data for maternal BMI exposure for BMI/anemia/LBWSG risk correlation
It is all an exact copy-paste from IV iron.
Artifact builds with new data
=> Model 5.0 Artifact

src/vivarium_gates_nutrition_optimization/components/children.py
- *Category*: 
misc
- *JIRA issue*: [MIC-4391](https://jira.ihme.washington.edu/browse/MIC-4391)
@hussain-jafari  needs this column in the child output data. for the child model.
Testing with next psim run
=> add pregnancy outcome to birth recorder

src/vivarium_gates_nutrition_optimization/components/children.py
- *Category*: 
misc
- *JIRA issue*: [MIC-4398](https://jira.ihme.washington.edu/browse/MIC-4398)
Per @hussain-jafari 
will confirm on next sim run
=> Change start date for child sim

src/vivarium_gates_nutrition_optimization/constants/data_keys.py, src/vivarium_gates_nutrition_optimization/data/extra_gbd.py, src/vivarium_gates_nutrition_optimization/data/loader.py
##Model 8.0 Artifact
- *Category*: 
artifact
- *JIRA issue*: [MIC-4392](https://jira.ihme.washington.edu/browse/MIC-4392)
- https://vivarium-research.readthedocs.io/en/latest/models/causes/other_causes/index.html#other-causes
Add the disability rate (i.e. per-simulant YLD rate) for background morbidity.
The considerations around what to include and exclude based on COMO are subtle and I am primarily following the documentation.
artifact can be built and contains new data key
=> Model 8.0 Artifact

src/vivarium_gates_nutrition_optimization/constants/metadata.py, src/vivarium_gates_nutrition_optimization/data/raw_data/coverage_by_scenario.csv, src/vivarium_gates_nutrition_optimization/model_specifications/branches/scenarios.yaml
- *Category*: 
implementation
- *JIRA issue*: [MIC-4456](https://jira.ihme.washington.edu/browse/MIC-4456)
https://github.com/ihmeuw/vivarium_research/pull/1309/files
RT wants a run with zero intervention coverage. This is as simple as adding it to the scenario coverage data value, and adding the scenario into the config.
tested in simulation, no simulants get interventions in zero coverage scenario.
=> Model 8.3 Zero Coverage Scenario

CHANGELOG.rst
- *Category*: 
misc
- *JIRA issue*: [MIC-4548](https://jira.ihme.washington.edu/browse/MIC-4548)
N/A
=> Add Changelog

src/vivarium_gates_nutrition_optimization/components/intervention.py, src/vivarium_gates_nutrition_optimization/components/observers.py
- *Category*: 
bugfix
- *JIRA issue*: [MIC-4551](https://jira.ihme.washington.edu/browse/MIC-4551)
Left out an erroneous difference of 2 timesteps
=> Update intervention time

src/vivarium_gates_nutrition_optimization/components/observers.py
- *Category*: 
refactor
- *JIRA issue*: [MIC-4416](https://jira.ihme.washington.edu/browse/MIC-4416)
Refactors custom observers
will wrap up and make sure simulation all runs smoothly when previous PRs merge
=> Refactor Observers

src/vivarium_gates_nutrition_optimization/components/hemoglobin.py, src/vivarium_gates_nutrition_optimization/components/intervention.py, src/vivarium_gates_nutrition_optimization/components/maternal_bmi.py
- *Category*: 
refactor
- *JIRA issue*: [MIC-4416](https://jira.ihme.washington.edu/browse/MIC-4416)
Refactors:
Hemoglobin
Anemia
Interventions
Maternal BMI
Sim Runs without errors
=> Refactor Anemia, Hemoglobin, Others

src/vivarium_gates_nutrition_optimization/constants/metadata.py, src/vivarium_gates_nutrition_optimization/data/raw_data/coverage_by_scenario.csv, src/vivarium_gates_nutrition_optimization/model_specifications/branches/scenarios.yaml
- *Category*: runs
- *JIRA issue*: [MIC-4779](https://jira.ihme.washington.edu/browse/MIC-4779)
Update targeted BEP/IFA scenario and include both targeted BEP scenarios.
Used breakpoint to verify that simulants with low BMI were assigned BEP and those with adequate BMI were assigned IFA in the updated scenario.
=> Final maternal production runs

src/vivarium_gates_nutrition_optimization/components/intervention.py, src/vivarium_gates_nutrition_optimization/components/observers.py
- *Category*: Observers
- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-XYZ)
-updates call order for mortality observer
Successfully ran simulation and saw expected outputs.
=> Fix mortality observer

src/vivarium_gates_nutrition_optimization/constants/data_keys.py, src/vivarium_gates_nutrition_optimization/constants/data_values.py, src/vivarium_gates_nutrition_optimization/constants/results.py, src/vivarium_gates_nutrition_optimization/data/loader.py, src/vivarium_gates_nutrition_optimization/model_specifications/model_spec.yaml, src/vivarium_gates_nutrition_optimization/results_processing/process_results.py
- *Category*:Other>
- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-XYZ)
-updates draw count in data_keys to not need vivarium inputs
-updates artifact path
-linting
=> Update to fix environment build

setup.py, src/vivarium_gates_nutrition_optimization/components/disease.py, src/vivarium_gates_nutrition_optimization/components/hemoglobin.py, src/vivarium_gates_nutrition_optimization/components/maternal_bmi.py, src/vivarium_gates_nutrition_optimization/components/morbidity.py, src/vivarium_gates_nutrition_optimization/components/mortality.py, src/vivarium_gates_nutrition_optimization/components/pregnancy.py, src/vivarium_gates_nutrition_optimization/model_specifications/model_spec.yaml
- *Category*: Refactor
- *JIRA issue*: [MIC-5061](https://jira.ihme.washington.edu/browse/MIC-5061)
-Updates components to use new lookup table configuration features.
Successfully ran simulation.
=> Mic 5061/lookup config update

.zenodo.json, README.rst
Files from Archiving that SHOULD be merged 
Files from Archiving that SHOULD be merged 
- *Category*: Other/misc 
- Updating the ORCID id file and the README.rst
=> Files from Archiving that SHOULD be merged 

.github/workflows/build.yml, src/vivarium_gates_nutrition_optimization/components/observers.py, src/vivarium_gates_nutrition_optimization/model_specifications/model_spec.yaml, src/vivarium_gates_nutrition_optimization/results_processing/process_results.py
- *Category*:  refactor
- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-5127)
Ran a short simulation and confirmed that values between old method and new
match exactly on the shared index or are otherwise all zero. 
I cannot attach my vv notebook (no support for .ipynb), but you can reference it at 
`/ihme/homes/sbachmei/notebooks/simscience/results-processing/vv-maternal-non-birth-recorder.ipynb`
=> update all standard Observers

.github/workflows/build.yml
- *Category*: CI
- *JIRA issue*: [MIC-5209](https://jira.ihme.washington.edu/browse/MIC-5209
- Don't install upstream dependencies inside package directory 
Tests pass
=> don't install upstream dependencies inside package directory

Jenkinsfile, Makefile, artifact_requirements.txt, environment.sh, requirements.txt
- *Category*: CI
- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-5213)
-install packages in Jenkins from requirements file
=> Mic-5213/conda-creation-CI

environment.sh
- *Category*: Feature
- *JIRA issue*: [MIC-5310](https://jira.ihme.washington.edu/browse/MIC-5310)
-adds n or new flag to make new environment
=> Mic-5310/Add new flag

Jenkinsfile
- *Category*: 
- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-XYZ)
- *Research reference*:
=> Update slack channel

environment.sh
- *Category*: Feature
- *JIRA issue*: [MIC-5272](https://jira.ihme.washington.edu/browse/MIC-5272)
-adds channel flag to environment creation script when installing conda packages
-this will make this script work with conda forge
=> Albrja/mic 5272/add channel flag

.github/workflows/build.yml
- *Category*: 
- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-XYZ)
- *Research reference*:
=> Add python version as arguement

Jenkinsfile, Makefile, setup.py
- *Category*: 
CI
- *JIRA issue*: [MIC-5796](https://jira.ihme.washington.edu/browse/MIC-5796)
- *Research reference*:
=> Use Shared Makefiles

Jenkinsfile
- *Category*: 
- *JIRA issue*: [MIC-5914](https://jira.ihme.washington.edu/browse/MIC-5914)
we refactored some of the logic of building; we need to change this to skip_doc_build instead.
=> Change skip_build to skip_doc_build
